# Data Acquisition

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

back to root to call functions from helpers.py file

In [2]:
import os
from pathlib import Path
print(Path.cwd())
os.chdir(Path('..').resolve())
from src.utils.helpers import save
print(Path.cwd())

/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning/notebooks
/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning

load train data

In [3]:
df_train = pd.read_csv(r'data/raw/train.csv', header=None, names=['review_target', 'review_title', 'review_content'], dtype=str, quoting=0)
df_train.head()

,review_target,review_title,review_content
0,2,Stuning even for the non-gamer,This sound track was beautiful! It paints the ...
1,2,The best soundtrack ever to anything.,I'm reading a lot of reviews saying that this ...
2,2,Amazing!,This soundtrack is my favorite music of all ti...
3,2,Excellent Soundtrack,I truly like this soundtrack and I enjoy video...
4,2,"Remember, Pull Your Jaw Off The Floor After He...","If you've played the game, you know how divine..."

In [4]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600000 entries, 0 to 3599999
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   review_target   str
 1   review_title    str
 2   review_content  str
dtypes: str(3)
memory usage: 82.4 MB

Due to the large dataset size, we will work on a random 80k for training and 20k for validation subset for faster iteration and development.

In [5]:
sample_train_valid = df_train.sample(n=100000, random_state=42).reset_index(drop=True)
sample_train_valid.head()

,review_target,review_title,review_content
0,1,Expensive Junk,This product consists of a piece of thin flexi...
1,1,Toast too dark,"Even on the lowest setting, the toast is too d..."
2,2,Excellent imagery...dumbed down story,I enjoyed this disc. The video is stunning. I ...
3,1,Are we pretending everyone is married?,The authors pretend that parents neither die n...
4,1,Not worth your time,"Might as well just use a knife, this product h..."

In [6]:
sample_train_valid.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   review_target   100000 non-null  str
 1   review_title    99993 non-null   str
 2   review_content  100000 non-null  str
dtypes: str(3)
memory usage: 2.3 MB

split train dataset to train 80% and valid 20%

In [7]:
sample_train, sample_valid = train_test_split(sample_train_valid, test_size=0.2, random_state=42, stratify=sample_train_valid['review_target'])
print(f"Training set size: {len(sample_train)}")
print(f"Validation set size: {len(sample_valid)}")

Training set size: 80000
Validation set size: 20000

show train dataset

In [8]:
sample_train.head()

,review_target,review_title,review_content
27835,2,"Good tool, good price",I received the tool in a timely fashion.Assemb...
12653,1,Not what I expected!,"This toy has alot of activities, but is not a ..."
91243,1,Not so great,"I wanted this hair wax for a while, and once I..."
71365,1,"Great hardware, but the PC software is terrible",The hardware functionality is excellent for ou...
88358,2,A must for anyone who cooks and bakes!!!,To say that i am pleased with my kitchenaid ar...

In [9]:
sample_train.info()

<class 'pandas.DataFrame'>
Index: 80000 entries, 27835 to 62374
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_target   80000 non-null  str
 1   review_title    79994 non-null  str
 2   review_content  80000 non-null  str
dtypes: str(3)
memory usage: 2.4 MB

save train dataset

In [10]:
save(base_path='data/samples', df=sample_train, df_name='sample_train.csv')

Saved dataframe to data/samples/sample_train.csv

{'csv': PosixPath('data/samples/sample_train.csv')}

show valid dataset

In [11]:
sample_valid.head()

,review_target,review_title,review_content
43433,2,Everything you need,This is a wonderful book. It may have been mea...
90016,1,Important note about carrier,"The carrier is very cute, and lightweight...ho..."
88845,1,Not a musical instrument -cannot be played,I bought (elsewhere) one of these harps for my...
46786,2,Do I Iike this monitor? Well... I have 2!,I have 2 of these babies hooked up to a dual-o...
21198,1,Very disappointing,This book is very poorly written and lacks of ...

In [12]:
sample_valid.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 43433 to 5820
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_target   20000 non-null  str
 1   review_title    19999 non-null  str
 2   review_content  20000 non-null  str
dtypes: str(3)
memory usage: 625.0 KB

save valid dataset

In [13]:
save(base_path='data/samples', df=sample_valid, df_name='sample_valid.csv')

Saved dataframe to data/samples/sample_valid.csv

{'csv': PosixPath('data/samples/sample_valid.csv')}

load test data

In [15]:
df_test = pd.read_csv(r'data/raw/test.csv', header=None, names=['review_target', 'review_title', 'review_content'], dtype=str, quoting=0)
df_test.head()

,review_target,review_title,review_content
0,2,Great CD,My lovely Pat has one of the GREAT voices of h...
1,2,One of the best game music soundtracks - for a...,Despite the fact that I have only played a sma...
2,1,Batteries died within a year ...,I bought this charger in Jul 2003 and it worke...
3,2,"works fine, but Maha Energy is better",Check out Maha Energy's website. Their Powerex...
4,2,Great for the non-audiophile,Reviewed quite a bit of the combo players and ...

In [16]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   review_target   400000 non-null  str
 1   review_title    399976 non-null  str
 2   review_content  400000 non-null  str
dtypes: str(3)
memory usage: 9.2 MB

Due to the large dataset size, we will work on a random 20k for testing subset for faster iteration and development.

In [17]:
sample_test = df_test.sample(n=20000, random_state=42).reset_index(drop=True)
sample_test.head()

,review_target,review_title,review_content
0,2,This is a great book,I must preface this by saying that I am not re...
1,1,Huge Disappointment.,"As a big time, long term Trevanian fan, I was ..."
2,2,Wayne is tight but cant hang with Turk.,This album is hot as it wants to be. However C...
3,2,Excellent,I read this book when I was in elementary scho...
4,1,Not about Anusara,Although this book is touted on several Anusar...

In [18]:
sample_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_target   20000 non-null  str
 1   review_title    19999 non-null  str
 2   review_content  20000 non-null  str
dtypes: str(3)
memory usage: 468.9 KB

save test dataset

In [19]:
save(base_path='data/samples', df=sample_test, df_name='sample_test.csv')

Saved dataframe to data/samples/sample_test.csv

{'csv': PosixPath('data/samples/sample_test.csv')}