# Data Preprocessing

Standardizing the text. because "garbage in, garbage out". We are removing HTML tags, making everything lowercase, and stripping out useless punctuation so the model doesn't get confused.

In [1]:
import pandas as pd

back to root to call functions from helpers.py file

In [2]:
import os
from pathlib import Path
print(Path.cwd())
os.chdir(Path('..').resolve())
from src.utils.helpers import clean_text, save
print(Path.cwd())

/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning/notebooks
/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning

load balanced dataset

In [3]:
balanced_sample_train = pd.read_csv(r'data/balanced/balanced_sample_train.csv', dtype=str, quoting=0, nrows=100)
balanced_sample_train.head()

,review_target,review_title,review_content,char_count,word_count
0,2,GREAT CAMRA,I HAVE HAD THE DX6340 FOR ABOUT A YEAR.I LOVE ...,586,108
1,1,not so great,I'm using this book in an introductory organic...,570,88
2,1,Inaccurate and disappointing,I only read the first few chapters and was bom...,214,40
3,1,Equus 3340,"Feels cheaply made, the battery contacts were ...",193,34
4,2,awesome sheets!,I love these sheets! They are sleek & smooth w...,198,38

In [4]:
balanced_sample_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_target   100 non-null    str
 1   review_title    100 non-null    str
 2   review_content  100 non-null    str
 3   char_count      100 non-null    str
 4   word_count      100 non-null    str
dtypes: str(5)
memory usage: 4.0 KB

apply cleaning

In [6]:
processed_train = balanced_sample_train.copy()
processed_train['review_cleaned'] = clean_text(processed_train['review_content'])
processed_train.head()

,review_target,review_title,review_content,char_count,word_count,review_cleaned
0,2,GREAT CAMRA,I HAVE HAD THE DX6340 FOR ABOUT A YEAR.I LOVE ...,586,108,dx6340 year love picture good 35m easy use unl...
1,1,not so great,I'm using this book in an introductory organic...,570,88,using book introductory organic spectroscopy c...
2,1,Inaccurate and disappointing,I only read the first few chapters and was bom...,214,40,read first chapter bombarded reference 199 end...
3,1,Equus 3340,"Feels cheaply made, the battery contacts were ...",193,34,feel cheaply made battery contact rusted soon ...
4,2,awesome sheets!,I love these sheets! They are sleek & smooth w...,198,38,love sheet sleek smooth really cool feel perfe...

Save the cleaned data

In [7]:
save(base_path='data/processed', df=processed_train, df_name='processed_train.csv')

Saved dataframe to data/processed/processed_train.csv

{'csv': PosixPath('data/processed/processed_train.csv')}