# Data Preprocessing

Standardizing the text. because "garbage in, garbage out". We are removing HTML tags, making everything lowercase, and stripping out useless punctuation so the model doesn't get confused.

In [1]:
import pandas as pd

back to root to call functions from helpers.py file

In [2]:
import os
from pathlib import Path
print(Path.cwd())
os.chdir(Path('..').resolve())
from src.utils.helpers import clean_text, save
print(Path.cwd())

e:\AI_ML\proj\sentiment-analysis-of-amazon-reviews-using-machine-learning-ml-queens\notebooks
E:\AI_ML\proj\sentiment-analysis-of-amazon-reviews-using-machine-learning-ml-queens

load balanced dataset

In [3]:
balanced_sample_train = pd.read_csv(r'data/processed/balanced_sample_train.csv', dtype=str, quoting=0)
balanced_sample_train.head()

,review_target,review_title,review_content,review_content_char_count,review_content_word_count
0,2,GREAT CAMRA,I HAVE HAD THE DX6340 FOR ABOUT A YEAR.I LOVE ...,586,108
1,1,not so great,I'm using this book in an introductory organic...,570,88
2,1,Inaccurate and disappointing,I only read the first few chapters and was bom...,214,40
3,1,Equus 3340,"Feels cheaply made, the battery contacts were ...",193,34
4,2,awesome sheets!,I love these sheets! They are sleek & smooth w...,198,38

In [4]:
balanced_sample_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 79972 entries, 0 to 79971
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   review_target              79972 non-null  str
 1   review_title               79972 non-null  str
 2   review_content             79972 non-null  str
 3   review_content_char_count  79972 non-null  str
 4   review_content_word_count  79972 non-null  str
dtypes: str(5)
memory usage: 3.1 MB

## Dataset Overview

The balanced training dataset contains a mix of positive and negative reviews, ensuring the model won't be biased towards one sentiment class. The columns include review content, titles, and targets, providing rich text data for sentiment analysis. This balanced approach is crucial for training reliable classifiers.

apply cleaning on training dataset

In [5]:
processed_train = balanced_sample_train.copy()
processed_train['review_content_cleaned'] = clean_text(processed_train['review_title'].fillna('') + ' ' + processed_train['review_content'].fillna(''))
processed_train.head()

,review_target,review_title,review_content,review_content_char_count,review_content_word_count,review_content_cleaned
0,2,GREAT CAMRA,I HAVE HAD THE DX6340 FOR ABOUT A YEAR.I LOVE ...,586,108,great camra dx6340 year love picture good 35m ...
1,1,not so great,I'm using this book in an introductory organic...,570,88,not great using book introductory organic spec...
2,1,Inaccurate and disappointing,I only read the first few chapters and was bom...,214,40,inaccurate disappointing read first chapter bo...
3,1,Equus 3340,"Feels cheaply made, the battery contacts were ...",193,34,equus 3340 feel cheaply made battery contact r...
4,2,awesome sheets!,I love these sheets! They are sleek & smooth w...,198,38,awesome sheet love sheet sleek smooth really c...

## Text Cleaning on Training Data

The cleaning process combines review titles and content, then removes HTML tags, converts to lowercase, and strips punctuation. This standardization ensures consistency across reviews and prevents the model from learning irrelevant patterns like capitalization or formatting differences. The cleaned text is now ready for vectorization.

apply cleaning on validation dataset
|

In [6]:
processed_valid = pd.read_csv(r'data/samples/sample_valid.csv', dtype=str, quoting=0)
processed_valid.head()

,review_target,review_title,review_content
0,2,Everything you need,This is a wonderful book. It may have been mea...
1,1,Important note about carrier,"The carrier is very cute, and lightweight...ho..."
2,1,Not a musical instrument -cannot be played,I bought (elsewhere) one of these harps for my...
3,2,Do I Iike this monitor? Well... I have 2!,I have 2 of these babies hooked up to a dual-o...
4,1,Very disappointing,This book is very poorly written and lacks of ...

In [7]:
processed_valid['review_content_cleaned'] = clean_text(processed_valid['review_title'].fillna('') + ' ' + processed_valid['review_content'].fillna(''))
processed_valid.head()

,review_target,review_title,review_content,review_content_cleaned
0,2,Everything you need,This is a wonderful book. It may have been mea...,everything need wonderful book may meant clerg...
1,1,Important note about carrier,"The carrier is very cute, and lightweight...ho...",important note carrier carrier very cute light...
2,1,Not a musical instrument -cannot be played,I bought (elsewhere) one of these harps for my...,not musical instrument cannot played bought el...
3,2,Do I Iike this monitor? Well... I have 2!,I have 2 of these babies hooked up to a dual-o...,iike monitor well baby hooked dual output digi...
4,1,Very disappointing,This book is very poorly written and lacks of ...,very disappointing book very poorly written la...

## Text Cleaning on Validation Data

Applying the same cleaning pipeline to validation data ensures consistency between training and validation sets. This prevents data leakage and maintains the integrity of model evaluation. The cleaned validation data will be used to tune hyperparameters and assess model performance.

apply cleaning on test dataset

In [8]:
processed_test = pd.read_csv(r'data/samples/sample_test.csv', dtype=str, quoting=0)
processed_test.head()

,review_target,review_title,review_content
0,2,This is a great book,I must preface this by saying that I am not re...
1,1,Huge Disappointment.,"As a big time, long term Trevanian fan, I was ..."
2,2,Wayne is tight but cant hang with Turk.,This album is hot as it wants to be. However C...
3,2,Excellent,I read this book when I was in elementary scho...
4,1,Not about Anusara,Although this book is touted on several Anusar...

In [9]:
processed_test['review_content_cleaned'] = clean_text(processed_test['review_content'])
processed_test.head()

,review_target,review_title,review_content,review_content_cleaned
0,2,This is a great book,I must preface this by saying that I am not re...,must preface saying not religious but loved bo...
1,1,Huge Disappointment.,"As a big time, long term Trevanian fan, I was ...",big time long term trevanian fan extremely dis...
2,2,Wayne is tight but cant hang with Turk.,This album is hot as it wants to be. However C...,album hot want however cash money best album e...
3,2,Excellent,I read this book when I was in elementary scho...,read book elementary school probably fourth gr...
4,1,Not about Anusara,Although this book is touted on several Anusar...,although book touted several anusara web site ...

## Text Cleaning on Test Content

Cleaning the test review content follows the same preprocessing steps as training data. This ensures the model receives input in the expected format during final evaluation. Separate cleaning of content and title allows for different feature engineering approaches if needed.

In [10]:
processed_test['review_title_cleaned'] = clean_text(processed_test['review_title'])
processed_test.head()

,review_target,review_title,review_content,review_content_cleaned,review_title_cleaned
0,2,This is a great book,I must preface this by saying that I am not re...,must preface saying not religious but loved bo...,great book
1,1,Huge Disappointment.,"As a big time, long term Trevanian fan, I was ...",big time long term trevanian fan extremely dis...,huge disappointment
2,2,Wayne is tight but cant hang with Turk.,This album is hot as it wants to be. However C...,album hot want however cash money best album e...,wayne tight but cannot hang turk
3,2,Excellent,I read this book when I was in elementary scho...,read book elementary school probably fourth gr...,excellent
4,1,Not about Anusara,Although this book is touted on several Anusar...,although book touted several anusara web site ...,not anusara

## Text Cleaning on Test Titles

Review titles often contain condensed sentiment information. Cleaning them separately allows for targeted feature extraction from titles, which can be more indicative of overall sentiment than full content. This completes the preprocessing pipeline for all datasets.

Save the cleaned data

In [11]:
save(df_base='data/processed', df=processed_train, df_name='processed_train.csv')

Saved dataframe processed_train.csv to data\processed\processed_train.csv

{'csv': WindowsPath('data/processed/processed_train.csv')}

In [12]:
save(df_base='data/processed', df=processed_valid, df_name='processed_valid.csv')

Saved dataframe processed_valid.csv to data\processed\processed_valid.csv

{'csv': WindowsPath('data/processed/processed_valid.csv')}

In [13]:
save(df_base='data/processed', df=processed_test, df_name='processed_test.csv')

Saved dataframe processed_test.csv to data\processed\processed_test.csv

{'csv': WindowsPath('data/processed/processed_test.csv')}