# Logistic Regression

Imports and helpers

In [3]:
import scipy.sparse as sp
import pandas as pd

back to root to call functions from helpers.py file

In [2]:
import os
from pathlib import Path
print(Path.cwd())
os.chdir(Path('..').resolve())
from src.utils.helpers import save
print(Path.cwd())

/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning/notebooks
/mnt/d/career/digilians/sentiment-analysis-of-amazon-reviews-using-machine-learning

In [10]:
X_train = sp.load_npz('data/vectorizers/X_train_tfidf.npz')
X_train.shape

(79972, 20000)

In [8]:
y_train = pd.read_csv('data/processed/y_train.csv')
y_train.head()

   review_target
0              2
1              1
2              1
3              1
4              2

In [11]:
X_valid = sp.load_npz('data/vectorizers/X_valid_tfidf.npz')
X_valid.shape

(20000, 20000)

In [12]:
y_valid = pd.read_csv('data/processed/y_valid.csv')
y_valid.head()

   review_target
0              2
1              1
2              1
3              2
4              1

In [13]:
X_test = sp.load_npz('data/vectorizers/X_test_tfidf.npz')
X_test.shape

(20000, 20000)

In [14]:
y_test = pd.read_csv('data/processed/y_train.csv')
y_test.head()

   review_target
0              2
1              1
2              1
3              1
4              2

## Model Training

## Model Evaluation

## Model Testing

In [ ]:
model.evaluate(X_test, y_test)

## Saving the Model and Pipeline

## Insights